import { useEffect, useState } from 'react';
import { MessageCircle, Wifi, WifiOff } from 'lucide-react';
import { PageHeader } from '../../components/ui/PageHeader';
import { marketingService } from '../../services/marketing.service';
import { useApp } from '../../context/AppContext';

export default function WhatsApp(){const{addToast}=useApp();const[connection,setConnection]=useState(null);const[messages,setMessages]=useState([]);const[flows,setFlows]=useState([]);const load=()=>Promise.all([marketingService.getWAStatus(),marketingService.listAutoMessages(),marketingService.listFlows()]).then(([c,m,f])=>{setConnection(c.data.data);setMessages(m.data.data?.data||m.data.data||[]);setFlows(f.data.data?.data||f.data.data||[])});useEffect(load,[]);
 const connect=async()=>{try{await marketingService.connectWA();await load();addToast('Solicitação enviada ao provedor WhatsApp','success')}catch(e){addToast(e.response?.data?.error?.message||'Falha ao conectar','error')}};
 const disconnect=async()=>{await marketingService.disconnectWA();await load()};
 return <div><PageHeader title="Automação WhatsApp" subtitle="Integração real com o provedor configurado"/><div className="card mb-5 flex items-center gap-4">{connection?.status==='connected'?<Wifi className="text-emerald-400"/>:<WifiOff className="text-red-400"/>}<div className="flex-1"><p className="text-white">Status: {connection?.status||'desconectado'}</p><p className="text-xs text-gray-500">{connection?.phoneNumber||'Nenhum número conectado'}</p></div>{connection?.status==='connected'?<button className="btn-secondary" onClick={disconnect}>Desconectar</button>:<button className="btn-primary" onClick={connect}>Conectar</button>}</div><div className="grid lg:grid-cols-2 gap-4"><div className="card"><h3 className="section-title mb-3">Mensagens automáticas</h3>{messages.map(m=><div key={m.id} className="p-3 border-b border-dark-400"><p className="text-white">{m.name}</p><p className="text-xs text-gray-500">{m.template}</p></div>)}</div><div className="card"><h3 className="section-title mb-3">Fluxos</h3>{flows.map(f=><div key={f.id} className="flex p-3 border-b border-dark-400"><MessageCircle size={14} className="text-gold mr-2"/><span className="text-white">{f.name}</span></div>)}</div></div></div>}
