import { useEffect, useState } from 'react';
import { Save, Plus } from 'lucide-react';
import { PageHeader } from '../../components/ui/PageHeader';
import { settingsService } from '../../services/settings.service';
import { useApp } from '../../context/AppContext';

export default function Configuracoes(){const{addToast}=useApp();const[shop,setShop]=useState({});const[users,setUsers]=useState([]);const[payments,setPayments]=useState({});const[newUser,setNewUser]=useState({name:'',email:'',password:'',role:'receptionist'});const load=()=>Promise.all([settingsService.getBarbershop(),settingsService.listUsers(),settingsService.getPaymentMethods()]).then(([s,u,p])=>{setShop(s.data.data);setUsers(u.data.data);setPayments(p.data.data)});useEffect(load,[]);
 const save=async()=>{await settingsService.updateBarbershop({...shop,intervalMinutes:Number(shop.intervalMinutes)});await settingsService.updatePaymentMethods(payments);addToast('Configurações salvas','success')};const create=async()=>{await settingsService.createUser(newUser);setNewUser({name:'',email:'',password:'',role:'receptionist'});await load();addToast('Usuário criado','success')};
 return <div><PageHeader title="Configurações" subtitle="Dados persistidos na API" actions={<button className="btn-primary" onClick={save}><Save size={14}/> Salvar</button>}/><div className="grid lg:grid-cols-2 gap-4"><div className="card space-y-3"><h3 className="section-title">Barbearia</h3>{['name','phone','whatsapp','email','address','city','state'].map(k=><input key={k} className="input" placeholder={k} value={shop[k]||''} onChange={e=>setShop({...shop,[k]:e.target.value})}/>)}<input className="input" type="number" value={shop.intervalMinutes||30} onChange={e=>setShop({...shop,intervalMinutes:e.target.value})}/><h3 className="section-title pt-3">Pagamentos</h3>{['pix','cash','credit','debit','subscription'].map(k=><label key={k} className="flex gap-2 text-sm text-gray-300"><input type="checkbox" checked={!!payments[k]} onChange={e=>setPayments({...payments,[k]:e.target.checked})}/>{k}</label>)}</div><div className="card"><h3 className="section-title mb-3">Usuários</h3>{users.map(u=><div key={u.id} className="p-3 border-b border-dark-400"><p className="text-white">{u.name}</p><p className="text-xs text-gray-500">{u.email} · {u.role}</p></div>)}<div className="space-y-2 mt-4"><input className="input" placeholder="Nome" value={newUser.name} onChange={e=>setNewUser({...newUser,name:e.target.value})}/><input className="input" placeholder="E-mail" value={newUser.email} onChange={e=>setNewUser({...newUser,email:e.target.value})}/><input className="input" type="password" placeholder="Senha" value={newUser.password} onChange={e=>setNewUser({...newUser,password:e.target.value})}/><select className="input" value={newUser.role} onChange={e=>setNewUser({...newUser,role:e.target.value})}><option value="admin">Admin</option><option value="barber">Barbeiro</option><option value="receptionist">Recepção</option></select><button className="btn-secondary w-full justify-center" onClick={create}><Plus size={14}/> Criar usuário</button></div></div></div></div>}
